spring.application.name=management-transactions-CB
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/management-transactions
spring.r2dbc.username=postgres
spring.r2dbc.password=root

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false

server.port=8081